
name: namaz_vakti
description: Namaz Vakti - prayer times app (Android-first Flutter project)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: ^9.0.2
  flutter_local_notifications: ^12.0.4
  provider: ^6.0.5
  flutter_qiblah: ^1.0.7
  shared_preferences: ^2.1.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/quran_sample.txt
    - assets/logo.png
